### ISSUE TITLE
Error while running script

### ISSUE THREAD

**Issue by marcinbauer-ohf** [pacjo/UTnotifier#2]
I've installed all requirements, and upgraded pip3, but Im getting this error:

`Exception in thread Thread-1 (listen):
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Traceback (most recent call last):
  File "/Users/marcinbauer/Downloads/UTnotifier-main/UTnotifier.py", line 39, in <module>
    keyboard.add_hotkey("r+ctrl+shift", lambda: rCtrlShiftHandler())
  File "/opt/homebrew/lib/python3.10/site-packages/keyboard/__init__.py", line 641, in add_hotkey
    self.run()
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/keyboard/__init__.py", line 294, in listen
    steps = parse_hotkey_combinations(hotkey)
  File "/opt/homebrew/lib/python3.10/site-packages/keyboard/__init__.py", line 573, in parse_hotkey_combinations
    _os_keyboard.listen(self.direct_callback)
  File "/opt/homebrew/lib/python3.10/site-packages/keyboard/_darwinkeyboard.py", line 430, in listen
    return tuple(tuple(combine_step(step)) for step in parse_hotkey(hotkey))
  File "/opt/homebrew/lib/python3.10/site-packages/keyboard/__init__.py", line 358, in parse_hotkey
    steps.append(tuple(key_to_scan_codes(key) for key in keys))
  File "/opt/homebrew/lib/python3.10/site-packages/keyboard/__init__.py", line 358, in <genexpr>
    raise OSError("Error 13 - Must be run as administrator")
OSError: Error 13 - Must be run as administrator
    steps.append(tuple(key_to_scan_codes(key) for key in keys))
  File "/opt/homebrew/lib/python3.10/site-packages/keyboard/__init__.py", line 324, in key_to_scan_codes
    raise ValueError('Key {} is not mapped to any known key.'.format(repr(key)), e)
ValueError: ("Key 'r' is not mapped to any known key.", ValueError('Unrecognized character: r'))`

Second thing, could you provide some more information on how to setup Apprise? (The apprise URLs in the JSON).
Thanks!

**Comment by pacjo** [comment]
I will take a look at the main issue tomorrow. (did you try running as admin? It shouldn't be required, but it's worth trying)

As for apprise:
documentation: https://github.com/caronc/apprise
in the credentials file you just have to put the apprise compatible urls. The simplest one would probably be `windows://` for desktop notifications (on windows). In this case no parameters are required, but things more complicated such as mqtt could require additional information. Tomorrow I will share my config, so you will have something to base your's on.

**Comment by marcinbauer-ohf** [comment]
Thanks!
I've tried with sudo, and I still get this:
`File "/Users/marcinbauer/Downloads/UTnotifier-main/UTnotifier.py", line 39, in <module>
    keyboard.add_hotkey("r+ctrl+shift", lambda: rCtrlShiftHandler())
  File "/opt/homebrew/lib/python3.10/site-packages/keyboard/__init__.py", line 641, in add_hotkey
    steps = parse_hotkey_combinations(hotkey)
  File "/opt/homebrew/lib/python3.10/site-packages/keyboard/__init__.py", line 573, in parse_hotkey_combinations
    return tuple(tuple(combine_step(step)) for step in parse_hotkey(hotkey))
  File "/opt/homebrew/lib/python3.10/site-packages/keyboard/__init__.py", line 358, in parse_hotkey
    steps.append(tuple(key_to_scan_codes(key) for key in keys))
  File "/opt/homebrew/lib/python3.10/site-packages/keyboard/__init__.py", line 358, in <genexpr>
    steps.append(tuple(key_to_scan_codes(key) for key in keys))
  File "/opt/homebrew/lib/python3.10/site-packages/keyboard/__init__.py", line 324, in key_to_scan_codes
    raise ValueError('Key {} is not mapped to any known key.'.format(repr(key)), e)
ValueError: ("Key 'r' is not mapped to any known key.", ValueError('Unrecognized character: r'))
`

Please mind I'm not a programmer, just someone kinda into some advanced stuff. I'm trying to run this on the latest macOS and I have a M1 MBA.

**Comment by pacjo** [comment]
Ok, I'm on windows, so troubleshooting will be a bit harder. From what I found `keyboard` library has some problems on mac. I will try changing the library this weekend, maybe it will help.
In the meantime could you just edit the `UTnotifier.py` and comment out lines 39 and 40? They aren't necessary, only shortcuts won't be working. It should look like this:
```
# keyboard.add_hotkey("r+ctrl+shift", lambda: rCtrlShiftHandler())
# keyboard.add_hotkey("q+ctrl+shift", lambda: qCtrlShiftHandler())
```

and for apprise:
```
{
    "user": "<mail>",
    "password": "<password>",
    "apprise_urls": [
        "windows://",
        "mqtt://192.168.1.13:1883/UTnotifier"
    ]
}
```

**Comment by marcinbauer-ohf** [comment]
Ok I got it to execute w/o an error, but I also don't have any feedback that it IS working? How can I know that? I just get back into the prompt.
Pardon me, but could you answer some questions that I have?
1. Does this notify about surveys, or tests? I'm new to UT, and I got one survey (just missed two, and didn't get an email from UT 😡).
2. How are you running it on your RPI with HA? I've got a miniPC running HaOS (not docker). Can I get this to run there?
3. Is mqtt://192.168.1.13:1883/UTnotifier this an example url of a mqtt that is running in HA? Or a standalone mqtt server that you have?
4. Currently I've added this as my HA url:
`hassio://admin@192.168.1.5/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI5YmEzZjllZGQyZmU0MmQ3OWY4MmZmNDJmMzRlMDVhNCIsImlhdCI6MTY3OTQyOTYyNiwiZXhwIjoxOTk0Nzg5NjI2fQ.HwRp5d8ioV8CfNxj-A794dClPilq0PByi_fPTCtPaMA"` is this correct? If this works, how can I access the notification via HA?

Many thanks!

**Comment by pacjo** [comment]
By default it will start a headless browser to reduce resource usage. You can disable this to see what exactly is it doing by adding `-dh` to the command (disable headless).

1. It notifies about the number of available tests by extracting the number from the website's title (e.g. `(3) Tests available`). UT sends emails very rarely and test come and go, so there's nothing wrong with missing some.
2. I'm running HA in docker on my old (headless) PC. For now this script is designed to work on a desktop PC, not a server. In the future I intend to make a docker container, but for no HA is only used to get notifications from the PC running the script to other devices.
3. I have a standalone mqtt server running (mosquito). This is because I run HA container, where traditional add-ons aren't available. This however shouldn't have any impact on the url. I don't remember exactly how the official mqtt add-on works, but I think the url would be the same.
4. Can't help with this. For notifications I'm using mqtt exclusively with HA receiving the messages from mqtt server. I will share the automation I'm using tomorrow.

**Comment by marcinbauer-ohf** [comment]
Ok! I've been able to run it and read the notification from HA! One problem is when I sleep my MBA I get an error and the script crashes:
<img width="990" alt="Screenshot 2023-03-22 at 22 51 47" src="https://user-images.githubusercontent.com/6719575/227046802-6012225c-51b1-4d97-9d88-252d545b9084.png">

Mind you I modified the script to push some test notifications, that is why its pushing "0" tests in the logs.

**Comment by pacjo** [comment]
Sorry for late reply. I underestimated the amount of work I have to do, so I won't be able to change the library this weekend. I will try to do it later in a week.

I'm aware of the sleep issue and I thought I fixed it, as it doesn't happen on my PC. I think it's related to not having network access after waking from sleep, when script tries to refresh the page.

**Comment by pacjo** [comment]
Well, this took some time. I did a major rewrite, it should be better now. Rough version is already on github, can you check if you still have this issue?

**Comment by marcinbauer-ohf** [comment]
There seems to be a driver version miss match.
![Screenshot 2023-10-12 at 11 02 54](https://github.com/pacjo/UTnotifier/assets/6719575/bf1a03ed-19de-44d9-ab67-c8603b83babf)

**Comment by pacjo** [comment]
Ok, so [webdriver_manager](https://github.com/SergeyPirogov/webdriver_manager) still isn't implemented (which means webdriver management doesn't happen automatically), sorry. The good news is that since 115 you shouldn't need external webdriver.

I think we just need to remove the remains of the old webdriver. Can you try:
`brew cleanup chromedriver`
or
`brew cask uninstall chromedriver`?

I know nothing about macos, this is taken from here: https://stackoverflow.com/questions/49156019/cant-remove-old-version-of-chromedriver-on-macos .

**Comment by marcinbauer-ohf** [comment]
I've cleared the driver and updated it via brew. Now there is a chrome window that pops up (so no headless?) and this is what happens:
![Screenshot 2024-01-04 at 13 17 47](https://github.com/pacjo/UTnotifier/assets/6719575/6d3ed4dd-e9a6-4529-904b-32c4b669523c)

**Comment by pacjo** [comment]
It looks like they changed URL for authentication, it shouldn't be hard to fix.

**Comment by marcinbauer-ohf** [comment]
@pacjo Yes, unfortunately I think UT did a lot of changes in their UI and right now they don't even display the amount of tests in the page title, which makes your script not work unfortunately.

I've googled other solutions and I've found an advanced scraping platform called https://apify.com/ They seem to have the tools to do this. I was able to create a basic webscraper actor to login and check wether there are tests (by looking for <empty-state> node), but I cannot get the count of tests since they load via an API call and this isn't seen by the webscraper. Unfortunately I don't know how to scrape their API to get this data (this is something a other developer told me to do).

Do you think of trying to do a webscraper for UT in the future?
